version: "3"

services:

  gateone:
    image: me450722457/cka_lab:gateone
    ports:
    - "8000:8000"
    hostname: kubectl
    networks:
    - frontend
    volumes:
    - ssh_key:/root/.ssh/
    - /root/.kube/:/root/.kube/

  lab:
    image: me450722457/cka_lab:lab
    entrypoint: /opt/entry.bash
    ports:
      - 80:80
    networks:
    - frontend
    environment:
      GATEONE_HTTP_SERVER: "47.52.219.131:8000"

networks:
  frontend: {}
volumes:
  ssh_key: {}
